"""Add flow_snapshot_id for connecting from execution to snapshot

Revision ID: 2b0869fd7878
Revises: f81120497324
Create Date: 2025-08-29 16:46:45.725544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b0869fd7878'
down_revision: Union[str, None] = 'f81120497324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_execution_queue', sa.Column('flow_snapshot_id', sa.String(), nullable=True), schema='workflow')
    op.create_foreign_key(None, 'flow_execution_queue', 'flow_snapshot', ['flow_snapshot_id'], ['id'], source_schema='workflow', referent_schema='workflow', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flow_execution_queue', schema='workflow', type_='foreignkey')
    op.drop_column('flow_execution_queue', 'flow_snapshot_id', schema='workflow')
    # ### end Alembic commands ###
