"""Add limit range of name of flow

Revision ID: 458877c4da5b
Revises: 2b0869fd7878
Create Date: 2025-09-03 14:25:40.470196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '458877c4da5b'
down_revision: Union[str, None] = '2b0869fd7878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "flow",
        "name",
        existing_type=sa.String(),
        type_=sa.String(100),
        schema='workflow',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "flow",
        "name",
        existing_type=sa.String(100),
        type_=sa.String(),
        schema='workflow',
    )
    # ### end Alembic commands ###
