"""Add kind at sys func schema

Revision ID: 48863dacf3e8
Revises: 6f14e26b5283
Create Date: 2025-08-19 17:08:46.044337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48863dacf3e8'
down_revision: Union[str, None] = '6f14e26b5283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_function', sa.Column('kind', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_function', 'kind')
    # ### end Alembic commands ###
