"""Add system function table

Revision ID: 4c3fb63cbb68
Revises: d568c8075ae9
Create Date: 2025-08-14 15:08:18.576622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3fb63cbb68'
down_revision: Union[str, None] = 'd568c8075ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_function',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('impl_namespace', sa.String(), nullable=False),
    sa.Column('impl_callable', sa.String(), nullable=False),
    sa.Column('python_libraries', sa.JSON(), nullable=True),
    sa.Column('param_schema', sa.JSON(), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_function_id'), 'system_function', ['id'], unique=False)
    op.create_index(op.f('ix_system_function_name'), 'system_function', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_function_name'), table_name='system_function')
    op.drop_index(op.f('ix_system_function_id'), table_name='system_function')
    op.drop_table('system_function')
    # ### end Alembic commands ###
