"""Initial migration

Revision ID: 5a894e222c68
Revises: a6463dac05c7
Create Date: 2025-08-11 14:11:41.780051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a894e222c68'
down_revision: Union[str, None] = 'a6463dac05c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow', sa.Column('max_retires', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('kind', sa.String(), nullable=True))
    op.add_column('task', sa.Column('impl_namespace', sa.String(), nullable=True))
    op.add_column('task', sa.Column('impl_callable', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'impl_callable')
    op.drop_column('task', 'impl_namespace')
    op.drop_column('task', 'kind')
    op.drop_column('flow', 'max_retires')
    # ### end Alembic commands ###
