"""Initial migration

Revision ID: a6463dac05c7
Revises: ee54784b251c
Create Date: 2025-08-08 15:23:33.347805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6463dac05c7'
down_revision: Union[str, None] = 'ee54784b251c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow', sa.Column('is_draft', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow', 'is_draft')
    # ### end Alembic commands ###
