"""Add schedule_options field to Flow

Revision ID: cd83264d9131
Revises: cba512008680
Create Date: 2025-08-26 14:58:04.749751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd83264d9131'
down_revision: Union[str, None] = 'cba512008680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow', sa.Column('schedule_options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow', 'schedule_options')
    # ### end Alembic commands ###
