"""Initial migration

Revision ID: ee54784b251c
Revises: 91ddf19ecb08
Create Date: 2025-08-08 15:21:22.867316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee54784b251c'
down_revision: Union[str, None] = '91ddf19ecb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow', sa.Column('active_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow', 'active_status')
    # ### end Alembic commands ###
