"""Add normalized payload column at flow snapshot

Revision ID: f81120497324
Revises: 55898d37d029
Create Date: 2025-08-29 10:20:34.454303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81120497324'
down_revision: Union[str, None] = '55898d37d029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_snapshot', sa.Column('normalized_payload', sa.JSON(), nullable=True), schema='workflow')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow_snapshot', 'normalized_payload', schema='workflow')
    # ### end Alembic commands ###
