"""Initial migration

Revision ID: 369fa4f69276
Revises: e99252f0ee14
Create Date: 2025-03-27 12:04:59.186519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '369fa4f69276'
down_revision: Union[str, None] = 'e99252f0ee14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge_ui', sa.Column('labelStyle', sa.JSON(), nullable=True))
    op.add_column('edge_ui', sa.Column('labelBgStyle', sa.JSON(), nullable=True))
    op.add_column('edge_ui', sa.Column('labelBgPadding', sa.JSON(), nullable=True))
    op.add_column('edge_ui', sa.Column('labelBgBorderRadius', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edge_ui', 'labelBgBorderRadius')
    op.drop_column('edge_ui', 'labelBgPadding')
    op.drop_column('edge_ui', 'labelBgStyle')
    op.drop_column('edge_ui', 'labelStyle')
    # ### end Alembic commands ###
