"""Add variable_id for dag_run_snapshot_task

Revision ID: 4d17b0d8c91a
Revises: 6055440e7f9c
Create Date: 2025-04-18 10:41:11.858801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d17b0d8c91a'
down_revision: Union[str, None] = '6055440e7f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airflow_dag_run_snapshot_task', sa.Column('variable_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airflow_dag_run_snapshot_task', 'variable_id')
    # ### end Alembic commands ###
