"""Add snapshot for dag_run_history

Revision ID: 6055440e7f9c
Revises: 6636390485bb
Create Date: 2025-04-18 09:48:27.986153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6055440e7f9c'
down_revision: Union[str, None] = '6636390485bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airflow_dag_run_snapshot_edge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dag_run_history_id', sa.String(), nullable=False),
    sa.Column('edge_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('labelStyle', sa.JSON(), nullable=True),
    sa.Column('labelBgStyle', sa.JSON(), nullable=True),
    sa.Column('labelBgPadding', sa.JSON(), nullable=True),
    sa.Column('labelBgBorderRadius', sa.Numeric(), nullable=True),
    sa.Column('style', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dag_run_history_id'], ['airflow_dag_run_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('airflow_dag_run_snapshot_task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dag_run_history_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('function_id', sa.String(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('style', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dag_run_history_id'], ['airflow_dag_run_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airflow_dag_run_snapshot_task')
    op.drop_table('airflow_dag_run_snapshot_edge')
    # ### end Alembic commands ###
