"""Add schedule for DAG

Revision ID: 63e9b88846b6
Revises: 4d17b0d8c91a
Create Date: 2025-06-13 11:27:35.295120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e9b88846b6'
down_revision: Union[str, None] = '4d17b0d8c91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_version', sa.Column('schedule', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow_version', 'schedule')
    # ### end Alembic commands ###
