"""Add is_loaded_by_airflow column to flow_version

Revision ID: 6636390485bb
Revises: fd3d61426f07
Create Date: 2025-04-17 11:43:22.928183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6636390485bb'
down_revision: Union[str, None] = 'fd3d61426f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_version', sa.Column('is_loaded_by_airflow', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow_version', 'is_loaded_by_airflow')
    # ### end Alembic commands ###
