"""Initial migration

Revision ID: 6f64eadc7830
Revises: 3635d18131d5
Create Date: 2025-03-25 09:08:45.719252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f64eadc7830'
down_revision: Union[str, None] = '3635d18131d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'decorator_parameters')
    op.drop_column('task', 'options')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('options', sa.TEXT(), nullable=True))
    op.add_column('task', sa.Column('decorator_parameters', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
