"""Initial migration

Revision ID: 76be622fec26
Revises: 
Create Date: 2025-03-20 13:54:28.349518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76be622fec26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_id'), 'flow', ['id'], unique=False)
    op.create_index(op.f('ix_flow_name'), 'flow', ['name'], unique=True)
    op.create_table('function_library',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('main_filename', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('function', sa.String(), nullable=True),
    sa.Column('operator_type', sa.String(), nullable=True),
    sa.Column('docker_image_tag', sa.String(), nullable=True),
    sa.Column('dependencies', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ui_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_index(op.f('ix_function_library_id'), 'function_library', ['id'], unique=False)
    op.create_table('function_input',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('function_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['function_library.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_function_input_id'), 'function_input', ['id'], unique=False)
    op.create_table('function_output',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('function_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['function_library.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_function_output_id'), 'function_output', ['id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('flow_id', sa.String(), nullable=False),
    sa.Column('function_id', sa.String(), nullable=True),
    sa.Column('variable_id', sa.String(), nullable=False),
    sa.Column('decorator', sa.String(), nullable=True),
    sa.Column('decorator_parameters', sa.String(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['function_id'], ['function_library.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.create_table('edge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('flow_id', sa.String(), nullable=True),
    sa.Column('from_task_id', sa.String(), nullable=True),
    sa.Column('to_task_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_task_id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_id'), 'edge', ['id'], unique=False)
    op.create_table('edge_ui',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('edge_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('style', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['edge_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_ui_id'), 'edge_ui', ['id'], unique=False)
    op.create_table('task_input',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_input_id'), 'task_input', ['id'], unique=False)
    op.create_table('task_ui',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('style', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_ui_id'), 'task_ui', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_ui_id'), table_name='task_ui')
    op.drop_table('task_ui')
    op.drop_index(op.f('ix_task_input_id'), table_name='task_input')
    op.drop_table('task_input')
    op.drop_index(op.f('ix_edge_ui_id'), table_name='edge_ui')
    op.drop_table('edge_ui')
    op.drop_index(op.f('ix_edge_id'), table_name='edge')
    op.drop_table('edge')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_function_output_id'), table_name='function_output')
    op.drop_table('function_output')
    op.drop_index(op.f('ix_function_input_id'), table_name='function_input')
    op.drop_table('function_input')
    op.drop_index(op.f('ix_function_library_id'), table_name='function_library')
    op.drop_table('function_library')
    op.drop_index(op.f('ix_flow_name'), table_name='flow')
    op.drop_index(op.f('ix_flow_id'), table_name='flow')
    op.drop_table('flow')
    # ### end Alembic commands ###
