"""Add file_hash column to flow_version table

Revision ID: c50daea9388d
Revises: ff4298f77c83
Create Date: 2025-04-16 14:35:29.477595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50daea9388d'
down_revision: Union[str, None] = 'ff4298f77c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_version', sa.Column('file_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow_version', 'file_hash')
    # ### end Alembic commands ###
