"""Initial migration

Revision ID: e99252f0ee14
Revises: 6f64eadc7830
Create Date: 2025-03-25 15:39:45.616454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99252f0ee14'
down_revision: Union[str, None] = '6f64eadc7830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function_input', sa.Column('sensitive', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('function_input', 'sensitive')
    # ### end Alembic commands ###
