"""Add file_hash column to flow_trigger_queue

Revision ID: fd3d61426f07
Revises: c50daea9388d
Create Date: 2025-04-16 15:08:05.969853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3d61426f07'
down_revision: Union[str, None] = 'c50daea9388d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_trigger_queue', sa.Column('file_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow_trigger_queue', 'file_hash')
    # ### end Alembic commands ###
