"""Add dag_id column in airflow_dag_run_history

Revision ID: ff4298f77c83
Revises: 22f504318666
Create Date: 2025-04-14 16:14:08.381790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4298f77c83'
down_revision: Union[str, None] = '22f504318666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airflow_dag_run_history', sa.Column('dag_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airflow_dag_run_history', 'dag_id')
    # ### end Alembic commands ###
