apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: workflow4graphio
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "1Gi"
      defaultRequest:
        cpu: "250m"
        memory: "512Mi"
      type: Container
