apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workflow-server
  name: workflow-server
  namespace: workflow4graphio
spec:
  selector:
    matchLabels:
      app: workflow-server
  replicas: 1
  template:
    metadata:
      labels:
        app: workflow-server
    spec:
      containers:
        - name: workflow-server
          image: repo.iris.tools/graphio/workflow/workflow-server:0.1.97-20250828-7f08368
          imagePullPolicy: IfNotPresent
          command:
            - /entrypoint.sh
          env:
            - name: DEBUG
              value: "True"
            - name: DB_TYPE
              value: "postgresql"
            - name: DB_HOST
              value: "postgresql-svc"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "graphio"
            - name: DB_SCHEMA
              value: "workflow"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "password"
            - name: AIRFLOW_DB_TYPE
              value: "postgresql"
            - name: AIRFLOW_DB_HOST
              value: "postgresql-svc"
            - name: AIRFLOW_DB_PORT
              value: "5432"
            - name: AIRFLOW_DB_NAME
              value: "graphio"
            - name: AIRFLOW_DB_SCHEMA
              value: "airflow"
            - name: AIRFLOW_DB_USERNAME
              value: "root"
            - name: AIRFLOW_DB_PASSWORD
              value: "password"
            - name: LOG_DIR
              value: "/app/logs"
            - name: DAG_DIR
              value: "/app/dags"
            - name: SHARED_DIR
              value: "/app/shared"
            - name: BUILTIN_FUNC_SCRIPT_DIR
              value: "/app/builtin_scripts"
            - name: AIRFLOW_HOST
              value: "airflow-svc"
            - name: AIRFLOW_PORT
              value: "8080"
            - name: AIRFLOW_USER
              value: "root"
            - name: AIRFLOW_PASSWORD
              value: "password"
          ports:
            - containerPort: 5050
              name: api-port
              protocol: TCP
          volumeMounts:
            - mountPath: /app/shared
              name: ext-volume
              subPath: airflow/shared
            - mountPath: /app/builtin_functions
              name: ext-volume
              subPath: airflow/builtin_functions
            - mountPath: /app/logs
              name: ext-volume
              subPath: workflow/logs
            - mountPath: /app/dags
              name: ext-volume
              subPath: airflow/dags
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 0
      volumes:
        - name: ext-volume
          persistentVolumeClaim:
            claimName: pvc-workflow4graphio
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: workflow-server
  name: workflow-server-svc
  namespace: workflow4graphio
spec:
  ports:
  - name: api-port
    port: 5050
    protocol: TCP
    targetPort: api-port
  selector:
    app: workflow-server
  type: NodePort
